language: node_js
node_js:
  - 12
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm run export
  - echo portfolios.uxwizards.org >> CNAME
  - touch out/.nojekyll
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: out
  on:
    branch: main
